"""
Travel Itinerary Word Export Service

Exports travel plans to Word documents with:
- Trip overview table
- Flight options
- Accommodation recommendations
- Dining recommendations
- Weather forecast
- Expert recommendations
"""

import logging
from io import BytesIO
from datetime import datetime
from typing import Dict, List, Any, Optional

logger = logging.getLogger(__name__)


class WordExportService:
    """
    Exports travel plans to Word documents.

    Creates formatted documents with sections for:
    - Trip overview
    - Flights, Hotels, Dining, Weather
    - Expert recommendations
    """

    def export_to_word(
        self,
        trip_config: Dict,
        trip_data: Optional[Dict],
        expert_responses: Dict[str, Any]
    ) -> BytesIO:
        """
        Export travel plan to Word document.

        Args:
            trip_config: Trip configuration (destination, dates, budget, etc.)
            trip_data: Real-time data (weather, flights, hotels, dining)
            expert_responses: Dict of expert name -> response

        Returns:
            BytesIO buffer containing Word document
        """
        try:
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.enum.table import WD_TABLE_ALIGNMENT
        except ImportError:
            logger.error("python-docx not installed. Run: pip install python-docx")
            raise RuntimeError("python-docx required for Word export. Install with: pip install python-docx")

        doc = Document()
        trip_data = trip_data or {}

        # Title
        destination = trip_config.get("destination", "Your Trip")
        title = doc.add_heading(f"Trip Plan: {destination}", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle with generation date
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(f"Generated on {datetime.now().strftime('%B %d, %Y')}")
        run.italic = True

        doc.add_paragraph()  # Spacer

        # Trip Overview Section
        self._add_overview_section(doc, trip_config)

        # Flight Options
        if trip_data.get("flights"):
            self._add_section(doc, "Flight Options", trip_data["flights"])

        # Accommodation
        if trip_data.get("hotels"):
            self._add_section(doc, "Accommodation", trip_data["hotels"])

        # Dining & Restaurants
        if trip_data.get("dining"):
            self._add_section(doc, "Dining & Restaurants", trip_data["dining"])

        # Weather Forecast
        if trip_data.get("weather"):
            self._add_section(doc, "Weather Forecast", trip_data["weather"])

        # Expert Recommendations
        if expert_responses:
            doc.add_heading("Expert Recommendations", level=1)

            for expert_name, response in expert_responses.items():
                doc.add_heading(expert_name, level=2)

                # Get content from response
                if isinstance(response, dict):
                    content = response.get("content", str(response))
                else:
                    content = str(response)

                # Add paragraphs (limit length for readability)
                self._add_formatted_text(doc, content[:3000])

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run("Generated by Travel Planner AI")
        run.italic = True
        run.font.size = Pt(10)

        # Save to buffer
        output = BytesIO()
        doc.save(output)
        output.seek(0)

        return output

    def _add_overview_section(self, doc, trip_config: Dict):
        """Add trip overview table."""
        from docx.shared import Inches, Pt
        from docx.enum.table import WD_TABLE_ALIGNMENT

        doc.add_heading("Trip Overview", level=1)

        # Create overview table
        table = doc.add_table(rows=6, cols=2)
        table.style = 'Table Grid'

        # Populate table
        data = [
            ("Destination", trip_config.get("destination", "Not specified")),
            ("Departure Date", trip_config.get("departure", "Not specified")),
            ("Return Date", trip_config.get("return_date", "Not specified")),
            ("Travelers", trip_config.get("travelers", "Not specified")),
            ("Budget", f"${trip_config.get('budget', 0):,} USD"),
            ("Origin", trip_config.get("origin", "Not specified") or "Not specified"),
        ]

        for i, (label, value) in enumerate(data):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[1].text = str(value)

            # Bold the labels
            for paragraph in row.cells[0].paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        doc.add_paragraph()  # Spacer

    def _add_section(self, doc, title: str, content: str):
        """Add a content section with heading."""
        doc.add_heading(title, level=1)
        self._add_formatted_text(doc, content)
        doc.add_paragraph()  # Spacer

    def _add_formatted_text(self, doc, text: str):
        """Add text with basic markdown-like formatting support."""
        if not text:
            return

        # Split into paragraphs
        paragraphs = text.split('\n\n')

        for para_text in paragraphs:
            if not para_text.strip():
                continue

            # Handle headers (## style)
            if para_text.strip().startswith('## '):
                header_text = para_text.strip()[3:]
                doc.add_heading(header_text, level=2)
                continue

            # Handle list items
            lines = para_text.split('\n')
            for line in lines:
                line = line.strip()
                if not line:
                    continue

                # Bullet points
                if line.startswith('- ') or line.startswith('* '):
                    p = doc.add_paragraph(line[2:], style='List Bullet')
                # Numbered lists
                elif len(line) > 2 and line[0].isdigit() and line[1] in '.):':
                    p = doc.add_paragraph(line[2:].strip(), style='List Number')
                # Table rows (markdown)
                elif line.startswith('|') and line.endswith('|'):
                    # Skip table formatting markers
                    if '---' in line:
                        continue
                    # Add as regular text for now
                    p = doc.add_paragraph(line)
                else:
                    # Regular paragraph
                    p = doc.add_paragraph()
                    # Handle bold (**text**)
                    self._add_text_with_formatting(p, line)

    def _add_text_with_formatting(self, paragraph, text: str):
        """Add text to paragraph with bold/italic support."""
        import re

        # Simple bold pattern matching
        parts = re.split(r'(\*\*[^*]+\*\*)', text)

        for part in parts:
            if part.startswith('**') and part.endswith('**'):
                # Bold text
                run = paragraph.add_run(part[2:-2])
                run.bold = True
            else:
                paragraph.add_run(part)


def export_travel_plan_to_word(
    trip_config: Dict,
    trip_data: Optional[Dict],
    expert_responses: Dict[str, Any]
) -> BytesIO:
    """
    Convenience function to export travel plan to Word.

    Args:
        trip_config: Trip configuration
        trip_data: Real-time travel data
        expert_responses: Expert recommendations

    Returns:
        BytesIO buffer containing Word document
    """
    service = WordExportService()
    return service.export_to_word(trip_config, trip_data, expert_responses)
